parameters:
#    aeyoll_symfony_php_spec_generator.example.class: Aeyoll\SymfonyPhpSpecGeneratorBundle\Example

services:
#    aeyoll_symfony_php_spec_generator.example:
#        class: %aeyoll_symfony_php_spec_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
