parameters:
   aeyoll_symfony_php_spec_generator.service.generator.class: Aeyoll\SymfonyPhpSpecGeneratorBundle\Service\GeneratorService

services:
   aeyoll_symfony_php_spec_generator.service.generator:
       class: %aeyoll_symfony_php_spec_generator.service.generator.class%
       arguments: [@service_container, @doctrine.orm.entity_manager]
